config {
  type: "assertion",
  database: constants.PROJECT_ID,
  schema: "stage_french_fragrance",
  description: "Vérifie qu'il n'y a pas de valeurs nulles dans les colonnes clés",
  tags: ["datamart"]
}

SELECT *
FROM ${ref("stage_french_fragrance", "stg_01_mart_weekly_sales")}
WHERE 
  key IS NULL
  OR sale_year IS NULL
  OR sale_week IS NULL
  OR store_name IS NULL
  OR collection IS NULL
  OR category IS NULL
  OR total_sales_eur IS NULL
  OR city IS NULL